export type CurrencyMeta = { name: string; country: string; flag: string }

// [currency name, country / region, ISO 3166-1 alpha-2 for the flag emoji]
const entries: Record<string, [string, string, string]> = {
  AED: ['UAE Dirham', 'United Arab Emirates', 'AE'],
  AFN: ['Afghan Afghani', 'Afghanistan', 'AF'],
  ALL: ['Albanian Lek', 'Albania', 'AL'],
  AMD: ['Armenian Dram', 'Armenia', 'AM'],
  ANG: ['Netherlands Antillean Guilder', 'Curaçao & Sint Maarten', 'CW'],
  AOA: ['Angolan Kwanza', 'Angola', 'AO'],
  ARS: ['Argentine Peso', 'Argentina', 'AR'],
  AUD: ['Australian Dollar', 'Australia', 'AU'],
  AWG: ['Aruban Florin', 'Aruba', 'AW'],
  AZN: ['Azerbaijani Manat', 'Azerbaijan', 'AZ'],
  BAM: ['Convertible Mark', 'Bosnia & Herzegovina', 'BA'],
  BBD: ['Barbadian Dollar', 'Barbados', 'BB'],
  BDT: ['Bangladeshi Taka', 'Bangladesh', 'BD'],
  BGN: ['Bulgarian Lev', 'Bulgaria', 'BG'],
  BHD: ['Bahraini Dinar', 'Bahrain', 'BH'],
  BIF: ['Burundian Franc', 'Burundi', 'BI'],
  BMD: ['Bermudian Dollar', 'Bermuda', 'BM'],
  BND: ['Brunei Dollar', 'Brunei', 'BN'],
  BOB: ['Bolivian Boliviano', 'Bolivia', 'BO'],
  BRL: ['Brazilian Real', 'Brazil', 'BR'],
  BSD: ['Bahamian Dollar', 'Bahamas', 'BS'],
  BTN: ['Bhutanese Ngultrum', 'Bhutan', 'BT'],
  BWP: ['Botswana Pula', 'Botswana', 'BW'],
  BYN: ['Belarusian Ruble', 'Belarus', 'BY'],
  BZD: ['Belize Dollar', 'Belize', 'BZ'],
  CAD: ['Canadian Dollar', 'Canada', 'CA'],
  CDF: ['Congolese Franc', 'DR Congo', 'CD'],
  CHF: ['Swiss Franc', 'Switzerland', 'CH'],
  CLF: ['Chilean Unit of Account', 'Chile', 'CL'],
  CLP: ['Chilean Peso', 'Chile', 'CL'],
  CNH: ['Chinese Yuan (Offshore)', 'China (Offshore)', 'CN'],
  CNY: ['Chinese Yuan Renminbi', 'China', 'CN'],
  COP: ['Colombian Peso', 'Colombia', 'CO'],
  CRC: ['Costa Rican Colón', 'Costa Rica', 'CR'],
  CUP: ['Cuban Peso', 'Cuba', 'CU'],
  CVE: ['Cape Verdean Escudo', 'Cape Verde', 'CV'],
  CZK: ['Czech Koruna', 'Czechia', 'CZ'],
  DJF: ['Djiboutian Franc', 'Djibouti', 'DJ'],
  DKK: ['Danish Krone', 'Denmark', 'DK'],
  DOP: ['Dominican Peso', 'Dominican Republic', 'DO'],
  DZD: ['Algerian Dinar', 'Algeria', 'DZ'],
  EGP: ['Egyptian Pound', 'Egypt', 'EG'],
  ERN: ['Eritrean Nakfa', 'Eritrea', 'ER'],
  ETB: ['Ethiopian Birr', 'Ethiopia', 'ET'],
  EUR: ['Euro', 'Eurozone', 'EU'],
  FJD: ['Fijian Dollar', 'Fiji', 'FJ'],
  FKP: ['Falkland Islands Pound', 'Falkland Islands', 'FK'],
  FOK: ['Faroese Króna', 'Faroe Islands', 'FO'],
  GBP: ['British Pound', 'United Kingdom', 'GB'],
  GEL: ['Georgian Lari', 'Georgia', 'GE'],
  GGP: ['Guernsey Pound', 'Guernsey', 'GG'],
  GHS: ['Ghanaian Cedi', 'Ghana', 'GH'],
  GIP: ['Gibraltar Pound', 'Gibraltar', 'GI'],
  GMD: ['Gambian Dalasi', 'Gambia', 'GM'],
  GNF: ['Guinean Franc', 'Guinea', 'GN'],
  GTQ: ['Guatemalan Quetzal', 'Guatemala', 'GT'],
  GYD: ['Guyanese Dollar', 'Guyana', 'GY'],
  HKD: ['Hong Kong Dollar', 'Hong Kong', 'HK'],
  HNL: ['Honduran Lempira', 'Honduras', 'HN'],
  HRK: ['Croatian Kuna', 'Croatia', 'HR'],
  HTG: ['Haitian Gourde', 'Haiti', 'HT'],
  HUF: ['Hungarian Forint', 'Hungary', 'HU'],
  IDR: ['Indonesian Rupiah', 'Indonesia', 'ID'],
  ILS: ['Israeli New Shekel', 'Israel', 'IL'],
  IMP: ['Manx Pound', 'Isle of Man', 'IM'],
  INR: ['Indian Rupee', 'India', 'IN'],
  IQD: ['Iraqi Dinar', 'Iraq', 'IQ'],
  IRR: ['Iranian Rial', 'Iran', 'IR'],
  ISK: ['Icelandic Króna', 'Iceland', 'IS'],
  JEP: ['Jersey Pound', 'Jersey', 'JE'],
  JMD: ['Jamaican Dollar', 'Jamaica', 'JM'],
  JOD: ['Jordanian Dinar', 'Jordan', 'JO'],
  JPY: ['Japanese Yen', 'Japan', 'JP'],
  KES: ['Kenyan Shilling', 'Kenya', 'KE'],
  KGS: ['Kyrgyzstani Som', 'Kyrgyzstan', 'KG'],
  KHR: ['Cambodian Riel', 'Cambodia', 'KH'],
  KID: ['Kiribati Dollar', 'Kiribati', 'KI'],
  KMF: ['Comorian Franc', 'Comoros', 'KM'],
  KRW: ['South Korean Won', 'South Korea', 'KR'],
  KWD: ['Kuwaiti Dinar', 'Kuwait', 'KW'],
  KYD: ['Cayman Islands Dollar', 'Cayman Islands', 'KY'],
  KZT: ['Kazakhstani Tenge', 'Kazakhstan', 'KZ'],
  LAK: ['Lao Kip', 'Laos', 'LA'],
  LBP: ['Lebanese Pound', 'Lebanon', 'LB'],
  LKR: ['Sri Lankan Rupee', 'Sri Lanka', 'LK'],
  LRD: ['Liberian Dollar', 'Liberia', 'LR'],
  LSL: ['Lesotho Loti', 'Lesotho', 'LS'],
  LYD: ['Libyan Dinar', 'Libya', 'LY'],
  MAD: ['Moroccan Dirham', 'Morocco', 'MA'],
  MDL: ['Moldovan Leu', 'Moldova', 'MD'],
  MGA: ['Malagasy Ariary', 'Madagascar', 'MG'],
  MKD: ['Macedonian Denar', 'North Macedonia', 'MK'],
  MMK: ['Myanmar Kyat', 'Myanmar', 'MM'],
  MNT: ['Mongolian Tögrög', 'Mongolia', 'MN'],
  MOP: ['Macanese Pataca', 'Macau', 'MO'],
  MRU: ['Mauritanian Ouguiya', 'Mauritania', 'MR'],
  MUR: ['Mauritian Rupee', 'Mauritius', 'MU'],
  MVR: ['Maldivian Rufiyaa', 'Maldives', 'MV'],
  MWK: ['Malawian Kwacha', 'Malawi', 'MW'],
  MXN: ['Mexican Peso', 'Mexico', 'MX'],
  MYR: ['Malaysian Ringgit', 'Malaysia', 'MY'],
  MZN: ['Mozambican Metical', 'Mozambique', 'MZ'],
  NAD: ['Namibian Dollar', 'Namibia', 'NA'],
  NGN: ['Nigerian Naira', 'Nigeria', 'NG'],
  NIO: ['Nicaraguan Córdoba', 'Nicaragua', 'NI'],
  NOK: ['Norwegian Krone', 'Norway', 'NO'],
  NPR: ['Nepalese Rupee', 'Nepal', 'NP'],
  NZD: ['New Zealand Dollar', 'New Zealand', 'NZ'],
  OMR: ['Omani Rial', 'Oman', 'OM'],
  PAB: ['Panamanian Balboa', 'Panama', 'PA'],
  PEN: ['Peruvian Sol', 'Peru', 'PE'],
  PGK: ['PNG Kina', 'Papua New Guinea', 'PG'],
  PHP: ['Philippine Peso', 'Philippines', 'PH'],
  PKR: ['Pakistani Rupee', 'Pakistan', 'PK'],
  PLN: ['Polish Złoty', 'Poland', 'PL'],
  PYG: ['Paraguayan Guaraní', 'Paraguay', 'PY'],
  QAR: ['Qatari Riyal', 'Qatar', 'QA'],
  RON: ['Romanian Leu', 'Romania', 'RO'],
  RSD: ['Serbian Dinar', 'Serbia', 'RS'],
  RUB: ['Russian Ruble', 'Russia', 'RU'],
  RWF: ['Rwandan Franc', 'Rwanda', 'RW'],
  SAR: ['Saudi Riyal', 'Saudi Arabia', 'SA'],
  SBD: ['Solomon Islands Dollar', 'Solomon Islands', 'SB'],
  SCR: ['Seychellois Rupee', 'Seychelles', 'SC'],
  SDG: ['Sudanese Pound', 'Sudan', 'SD'],
  SEK: ['Swedish Krona', 'Sweden', 'SE'],
  SGD: ['Singapore Dollar', 'Singapore', 'SG'],
  SHP: ['Saint Helena Pound', 'St Helena', 'SH'],
  SLE: ['Sierra Leonean Leone', 'Sierra Leone', 'SL'],
  SLL: ['Sierra Leonean Leone (old)', 'Sierra Leone', 'SL'],
  SOS: ['Somali Shilling', 'Somalia', 'SO'],
  SRD: ['Surinamese Dollar', 'Suriname', 'SR'],
  SSP: ['South Sudanese Pound', 'South Sudan', 'SS'],
  STN: ['São Tomé Dobra', 'São Tomé & Príncipe', 'ST'],
  SYP: ['Syrian Pound', 'Syria', 'SY'],
  SZL: ['Eswatini Lilangeni', 'Eswatini', 'SZ'],
  THB: ['Thai Baht', 'Thailand', 'TH'],
  TJS: ['Tajikistani Somoni', 'Tajikistan', 'TJ'],
  TMT: ['Turkmenistani Manat', 'Turkmenistan', 'TM'],
  TND: ['Tunisian Dinar', 'Tunisia', 'TN'],
  TOP: ['Tongan Paʻanga', 'Tonga', 'TO'],
  TRY: ['Turkish Lira', 'Türkiye', 'TR'],
  TTD: ['Trinidad & Tobago Dollar', 'Trinidad & Tobago', 'TT'],
  TVD: ['Tuvaluan Dollar', 'Tuvalu', 'TV'],
  TWD: ['New Taiwan Dollar', 'Taiwan', 'TW'],
  TZS: ['Tanzanian Shilling', 'Tanzania', 'TZ'],
  UAH: ['Ukrainian Hryvnia', 'Ukraine', 'UA'],
  UGX: ['Ugandan Shilling', 'Uganda', 'UG'],
  USD: ['US Dollar', 'United States', 'US'],
  UYU: ['Uruguayan Peso', 'Uruguay', 'UY'],
  UZS: ['Uzbekistani Som', 'Uzbekistan', 'UZ'],
  VES: ['Venezuelan Bolívar', 'Venezuela', 'VE'],
  VND: ['Vietnamese Đồng', 'Vietnam', 'VN'],
  VUV: ['Vanuatu Vatu', 'Vanuatu', 'VU'],
  WST: ['Samoan Tālā', 'Samoa', 'WS'],
  YER: ['Yemeni Rial', 'Yemen', 'YE'],
  ZAR: ['South African Rand', 'South Africa', 'ZA'],
  ZMW: ['Zambian Kwacha', 'Zambia', 'ZM'],
  ZWG: ['Zimbabwe Gold', 'Zimbabwe', 'ZW'],
  ZWL: ['Zimbabwean Dollar (old)', 'Zimbabwe', 'ZW'],
}

// Supra-national currencies have no single country flag; use a region glyph.
const overrides: Record<string, [string, string, string]> = {
  XAF: ['Central African CFA Franc', 'Central African States', '🌍'],
  XCD: ['East Caribbean Dollar', 'East Caribbean States', '🌐'],
  XCG: ['Caribbean Guilder', 'Curaçao', 'CW'],
  XDR: ['IMF Special Drawing Rights', 'International Monetary Fund', '🌐'],
  XOF: ['West African CFA Franc', 'West African States', '🌍'],
  XPF: ['CFP Franc', 'French Pacific Territories', '🌐'],
}

const symbols: Record<string, string> = {
  USD: '$', EUR: '€', GBP: '£', JPY: '¥', CNY: '¥', CNH: '¥',
  INR: '₹', KRW: '₩', VND: '₫', THB: '฿', TRY: '₺', RUB: '₽',
  UAH: '₴', ILS: '₪', CHF: 'Fr', AUD: 'A$', NZD: 'NZ$', CAD: 'C$',
  SGD: 'S$', HKD: 'HK$', MXN: 'MX$', BRL: 'R$', ZAR: 'R', PLN: 'zł',
  SEK: 'kr', NOK: 'kr', DKK: 'kr', ISK: 'kr', CZK: 'Kč', HUF: 'Ft',
  PHP: '₱', IDR: 'Rp', MYR: 'RM', SAR: '﷼', AED: 'د.إ',
}

function regionalFlag(countryCode: string): string {
  return String.fromCodePoint(
    ...[...countryCode.toUpperCase()].map((char) => 0x1f1e6 + char.charCodeAt(0) - 65),
  )
}

export const currencyMeta: Record<string, CurrencyMeta> = Object.fromEntries(
  Object.entries({ ...entries, ...overrides }).map(([code, [name, country, cc]]) => [
    code,
    // Override entries already carry a glyph in place of the country code.
    { name, country, flag: cc.length === 2 ? regionalFlag(cc) : cc },
  ]),
)

export function metaFor(code: string): CurrencyMeta {
  return currencyMeta[code.toUpperCase()] ?? { name: code, country: '—', flag: '🏳' }
}

export function symbolFor(code: string): string | undefined {
  return symbols[code.toUpperCase()]
}
